spring:
  application:
    name: sd-implementation-challenge
  otel:
    tracing:
      sampling:
        probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

rate-limiter:
  capacity: 10
  refill-rate-per-second: 5

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always

