name: CD

on:
  workflow_run:
    workflows: [CI]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@25ce8cbbcb08177468c7ff7ec5cbfa236f9341e1 # v1.1.0
        env:
          REPO_PATH: ${{ secrets.EC2_REPO_PATH }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: REPO_PATH
          script: |
            cd "$REPO_PATH"
            git pull
            docker compose up --build -d app
